**Q-Learning idea:** training an agent to navigate a pupolar enviornment form the Open AI gym.

In [3]:
#Import open ai gym 
import gym

In [4]:
#loading an enviorment 

env = gym.make('FrozenLake-v1')


/usr/local/lib/python3.8/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.8/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [5]:
print(env.observation_space.n)  #number of states
print(env.action_space.n) #number of actions


16
4


In [6]:
env.reset()


0

In [7]:
action = env.action_space.sample()
print(action)

2


In [8]:
observation , reward , done , info = env.step(action)


In [9]:
!pip install pygame

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 74.0 MB/s eta 0:00:00


In [10]:
#env.render()

**Creating the Q table**

In [11]:
import gym 
import numpy as np 
import time 

env = gym.make('FrozenLake-v1')
States = env.observation_space.n
Actions = env.action_space.n

In [12]:
#Create matrix with 0  values 
Q = np.zeros((States, Actions))

Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
Episods = 10000
Max_steps = 100
Learning_rate =0.81
Gamma = 0.96

RENDER = False 


In [14]:
epsilon = 0.9 #random of picking actions 

if np.random.uniform(0,1) < epsilon: #checking if the rnadom value is inferieur than epsilon 
  action = env.action_space.sample()  #taking a random action
else: 
  action = np.argmax(Q[state, :]) #use the q table 




In [15]:
#Formule of updating
Q[state, action] = Q[state, action] +Learning_rate*(reward +Gamma*np.max(Q[state,:]) - Q[state, action] )

NameError: ignored

In [18]:

Rewards = []

for episode in range(Episods): 
  state = env.reset()
  for n in range(Max_steps):
    if RENDER:
      env.render()
    if np.random.uniform(0,1) < epsilon:
      action = env.action_space.sample()
    else : 
      action = np.argmax(Q[state,:])

    next_state , reward , done , _ = env.step(action)

    Q[state, action] = Q[state, action] +Learning_rate*(reward +Gamma*np.max(Q[next_state,:]) - Q[state, action] )
    
    state = next_state 

    if done : 
      Rewards.append(reward)
      epsilon -= 0.001
      break
    

print(Q)
print(f"Average rewards: {sum(Rewards)/len(Rewards)} ")




  

[[6.76325858e-04 9.03175958e-04 3.13380120e-01 1.00427930e-03]
 [6.07749964e-04 8.35223680e-04 5.51175215e-04 1.08425975e-01]
 [7.22040630e-04 3.58387231e-04 6.67890450e-04 3.58499002e-02]
 [2.84183904e-04 4.75261847e-04 2.95659185e-04 1.05920699e-02]
 [4.61574428e-01 6.12775711e-04 2.28028779e-04 1.21416174e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.20148896e-03 1.05218819e-06 1.48888142e-06 1.26846383e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.13393477e-04 2.95715227e-04 6.02288806e-04 6.62086265e-01]
 [2.34494703e-04 6.64455775e-01 2.77504119e-04 3.23865269e-04]
 [1.55619679e-01 5.41325832e-05 2.90816047e-05 9.95113415e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.74220047e-02 2.30682832e-02 8.58590197e-01 2.86627695e-02]
 [9.35926042e-02 9.88384111e-01 6.98465418e-02 9.74117602e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000